name: Publish && Release

on:
  push:
    branches:
    - develop

permissions:
  contents: read
  packages: write
  actions: read
  security-events: write
  pull-requests: write

jobs:
  ci:
    uses: ./.github/workflows/ci-maven.yml
    secrets: inherit

  gates:
    uses: ./.github/workflows/ci-gates.yml
    if: success()
    needs: ci
    secrets: inherit

  snapshot:
    needs: gates
    uses: ./.github/workflows/cd-snapshot.yml
    secrets: inherit

  pull-request:
    uses: ./.github/workflows/ci-pull-request.yml
    needs: snapshot
    secrets: inherit
    with:
      type: Release
      labels: automatic,release
      target-branch: master