name: Publish package to the Maven Central Repository

on:
  workflow_call:

jobs:
  publish:
    environment: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'corretto'
          server-id: sonatype-central
          server-username: OSSRH_USERNAME
          server-password: OSSRH_TOKEN
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Publish Release to the Maven Central Repository
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version | grep -e '^[^\[]' | grep -Eo '[0-9]\.[0-9]+')
          RELEASE_VERSION=${VERSION}
          RELEASE_TAG=v${RELEASE_VERSION}

          echo ${VERSION}
          echo ${RELEASE_VERSION}
          echo ${RELEASE_TAG}

          # mvn -B release:prepare release:perform -DreleaseVersion=${RELEASE_VERSION} -Dtag=${RELEASE_TAG} -P release
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
