name: Snapshot && Release

on:
  push:
    branches:
    - develop
    - master

permissions:
  contents: read
  packages: write
  actions: read
  security-events: write
  pull-requests: write

env:
  type: ${{ startsWith(github.ref, 'refs/heads/develop') && 'snapshot' || 'release'}}

jobs:
  ci:
    uses: ./.github/workflows/ci-maven.yml
    secrets: inherit

  gates:
    uses: ./.github/workflows/ci-gates.yml
    if: success()
    needs: ci
    secrets: inherit

  snapshot:
    if: ${{ github.env.type == 'snapshot' }}
    needs: gates
    uses: ./.github/workflows/cd-snapshot.yml
    secrets: inherit

  release:
    if: ${{ github.env.type == 'release' }}
    needs: gates
    uses: ./.github/workflows/cd-release.yml
    secrets: inherit

  pull-request:
    if: ${{ github.env.type == 'snapshot' }}
    uses: ./.github/workflows/ci-pull-request.yml
    needs: snapshot
    secrets: inherit
    with:
      type: Release
      labels: automatic,release
      target-branch: master