name: Build and Pull Request

on:
  push:
    branches:
    - feature/**
    - fix/**
    paths-ignore:
    - "**/README.md"
    - "**/CONTRIBUTING.md"
    - "**/CONTRIBUTORS.txt"
    - "**/LICENSE"

env:
  type: ${{ startsWith(github.ref, 'refs/heads/feature') && 'Feature' || 'Fix'}}
  labels: ${{ startsWith(github.ref, 'refs/heads/feature') && 'automatic,feature' || 'automatic,fix' }}
  target-branch: develop

permissions:
  contents: write
  actions: read
  security-events: write
  pull-requests: write

jobs:
  ci:
    uses: ./.github/workflows/ci-maven.yml
    secrets: inherit

  gates:
    uses: ./.github/workflows/ci-gates.yml
    if: success()
    needs: ci
    secrets: inherit
  
  pull-request:
    uses: ./.github/workflows/ci-pull-request.yml
    needs: gates
    secrets: inherit
    with:
      type: ${{ github.env.type }}
      labels: ${{ github.env.labels }}
      target-branch: ${{ github.env.target-branch }}
